# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{assembly_line}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sandro Turriate"]
  s.date = %q{2010-02-10}
  s.description = %q{Assembly Line allows you to group together a series of rspec `let` statements which can later be evaluated to set up a specific state for your specs.}
  s.email = %q{sandro.turriate@gmail.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.md",
     "MIT_LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "assembly_line.gemspec",
     "lib/assembly_line.rb",
     "lib/assembly_line/constructor.rb",
     "lib/assembly_line/generic_context.rb",
     "lib/assembly_line/registry.rb",
     "spec/assembly_line/constructor_spec.rb",
     "spec/assembly_line/generic_context_spec.rb",
     "spec/assembly_line/registry_spec.rb",
     "spec/assembly_line_spec.rb",
     "spec/functional/assemble_spec.rb",
     "spec/functional/global_context_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sandro/assembly_line}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Modularize setup blocks for rspec}
  s.test_files = [
    "spec/assembly_line/constructor_spec.rb",
     "spec/assembly_line/generic_context_spec.rb",
     "spec/assembly_line/registry_spec.rb",
     "spec/assembly_line_spec.rb",
     "spec/functional/assemble_spec.rb",
     "spec/functional/global_context_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["= 1.2.9"])
      s.add_development_dependency(%q<yard>, ["= 0.5.3"])
    else
      s.add_dependency(%q<rspec>, ["= 1.2.9"])
      s.add_dependency(%q<yard>, ["= 0.5.3"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 1.2.9"])
    s.add_dependency(%q<yard>, ["= 0.5.3"])
  end
end

